In [1]:
import numpy as np


In [4]:
new_arr=np.arange(100)

In [5]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
my_list = list(range(1_000_000))

In [9]:
%timeit my_arr2 = new_arr * 2


790 ns ± 32.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
%timeit my_list2 = [x * 2 for x in my_list]

51.3 ms ± 2.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [12]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [14]:
data1=np.array([1,2,3,45,2])

In [15]:
data1

array([ 1,  2,  3, 45,  2])

In [16]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [17]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])